---

- name: Teardown Webservers
  hosts: webservers
  gather_facts: false
  become: true
  tags:
    - teardown_webservers

  tasks:
    - name: Remove Webserver Packages
      package:
        name:
          - httpd
          - mod_wsgi 
        state: absent
